Upcoming events
MetaProvide/adminly_dashboard pull request #11
Opened 2022-03-22 11:06 UTC by oliveiraigorm

2022-03-23 11:52 UTC, frozenbanana requested changes
Can we get the coming three events instead of within a timespan?
I prefer a function that formats with template strings.

Also, the events are bound to the calendar name "Personal" we should consider the case when the user has more than one calendar.


```js
const getEventsUrl = (userName, calendarName) => (`/remote.php/dav/calendars/${userName}/${calendarName}?accept=jcal&componentType=VEVENT`)
```

then

```js
mounted() {
axios
  .get(getEventsUrl(userName, calName))
  ..
```


Also, I think it makes sense to have util functions to fetch the data we want from the repsonse. It makes it more readable. 

`id: element[1][4][3],` -> `id: getId(element)`

`title: element[1][8][3],` -> `id: getTitle(element)`

etc.


Also, I prefer to keep functions pure so instead of mutating `calendarEvents` with unshift, use `.map(fn)`

```js
calendarEvents = getEventsObjects(response.data).map(element=> ({id: getId(element), title: getTitle(element), ... }) )
```

2022-03-23 12:07 UTC, oliveiraigorm commented
> Can we get the coming three events instead of within a timespan?

No the plugin can only limit by time span. What I could do is to get the events within a certain time span or only the future events, to avoid getting the entire calendar, and limit to display only the 3 more recent ones.

2022-03-23 19:40 UTC, frozenbanana commented on src/components/Events.vue
> +
import {getId, getUserName, .. } from '../utils';

2022-03-24 12:32 UTC, frozenbanana commented on src/utils.js
> +	.getAttribute("data-user-displayname");
`.getAttribute("data-user-displayname")` should be `.getAttribute("data-user");`

2022-03-24 17:04 UTC, frozenbanana approved these changes

2022-03-25 09:13 UTC, merged